---
- name: First project with Ansible
  hosts: maria
  remote_user: maria
  become: yes
  become_method: sudo

  tasks: 
    - name: installing postgres
      apt:
        name:
          - postgresql
        state: latest

        # https://docs.ansible.com/ansible/2.5/modules/postgresql_user_module.html
    - name: creating a user for postgresql
      become: yes
      become_user: postgres
      postgresql_user:
        name: "maria"
        password: "password"

    - name: installing packages
      apt: 
        name:
          - git
          - zsh
          - python-pip
          - python3-pip
          - postgresql
        state: latest

    - name: install psycopg2-binary and Flask with pip3
      pip: 
        name:
          - psycopg2-binary     
          - python3-flask
      executable: pip3
      status: latest


    - name: clone git repository
      git:
        repo: https://github.com/MarriaMarria/Ansible
        dest: /home/maria/Projects/Ansible
        update: yes
        # force: yes

    - name: create database
      become: yes
      become_user: postgres
      postgresql_db:
        name: "maria_db"
        owner: "postgres"execute script 

    - name: executing script connection_db.python
      command: python3 ./

    - name: executing script rounting.python
      command: python3 ./
      # git:
      #   repo: "https://github.com/{{ github_user }}/{{ app_name }}.git"
      #   dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
      #   update: yes # Does a git pull if the repo already exists

...
    
